  - (0) PARENT=; SEQ=1; NOTE=indented right away is okay
    some text under list item
* heading 1
  - (1) PARENT=; SEQ=1; NOTE=headline resets last listitem
* heading 2
  - (2) PARENT=; SEQ=1
    - (3) PARENT=2; SEQ=1
      this text still belongs to the list item
    + (4) PARENT=2; SEQ=1; NOTE=different bullet style belongs to different list
     this text still belongs to the list item
    + (5) PARENT=2; SEQ=2
    + (6) dt :: PARENT=2; SEQ=1; NOTE=description list differs from (un)ordered list
    - [X](7) PARENT=2; SEQ=1; NOTE=different bullet style belongs to different list
      * (8) PARENT=7; SEQ=1
        1. (9) PARENT=8; SEQ=1
        3. (10) PARENT=8; SEQ=2
        4. (11) PARENT=8; SEQ=3
          + (12) PARENT=11
  - (13) PARENT=; SEQ=2
      * (14) PARENT=13; SEQ=1
* heading 3 - description list
- (15) term1 :: value1
- (16) t2    ::value2
* heading 4 - indenting rule
this is the new org-mode 7.x(?) behavior, where if there is a text under a list
item indented at the same level as or less than the list item, it breaks the
list.
 - (17) list(12)
  - (18) list(13) [2013-01-01 ]
  this text(1) breaks the list(13)
  but is still included as child of list(12)
  - (19) list(14)
 - (20)
this text(2) breaks the list(12)
 - (21) list(15)
* heading 5 - list should not be broken by a single blank line
list should not be broken by just one blank line
- (22) a list (16)
- (23) b list (16)

  - (24) c (this should still be the child of item b) list (17)
* heading 6 - list should be broken by two blank lines
but list can be broken using two blank lines
- (25) d list (18)

  - (26) e (should be a child of item d) list (19)


    - (27) f (should be child of headline, not d nor e) list (20)
* heading 7 - when can list item become parent?
list item can become parent for other block elements except: setting, headline
because they are not indentable. other block elements (other list item, fixed
width section, comment, table, drawer) can be child item if they are more
indented. otherwise, they become child for less-indented list item or headline
or document.

- (28) list item, list (21)
 | col1 | col2 |
 |------+------+
 | a    | b    |
- (29) list item, list (21)
| col1 | col2 |
|------+------+
| a    | b    |
- (30) list item, list (22)
 :DRAWER:
 :END:
- (31) list item, list (22)
:DRAWER:
:END:
- (32) list item, list (23)
 # COMMENT
- (33) list item, list (23)
# COMMENT
- (34) list item, list (24)
 : fixed width
- (35) list item, list (24)
: fixed width
- (36) list item, list (25)
#+TODO: TODO | DONE
